### ISSUE TITLE
ChartType.axis_mixed does not work

### ISSUE THREAD

**Issue by rscataran** [tolbxela/FrappeCharts.NET#1]
I have been trying this wrapper for Frappe Charts with the sample provided on https://frappe.io/charts/docs#usage

The Chart Type used on the sample  is "axis-mixed". Selecting  ChartType.axis_mixed produces an error on the generated javascript. the "axis_mixed" is not a valid chart type.

I  suggest to put a [EnumMember(Value = "axis-mixed")] attribute on axis_mixed member on ChartTypes enum to correctly serialize the value.

**Comment by tolbxela** [comment]
Thanks for info! You can make a PR, if you like.

**Comment by rscataran** [comment]
I'll just leave this info here for anyone else who would like to use this. Thanks.
